apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odoo
  namespace: argocd
spec:
  project: default
  source:
    chart: bitnami/odoo
    repoURL: https://charts.bitnami.com/bitnami/odoo
    targetRevision: 23.0.3
    helm:
      releaseName: odoo
  destination:
    server: "https://kubernetes.default.svc"
    namespace: odoo